"use client";

import { startTransition, useState } from "react";
import { Checkbox, Flex, Select, Text } from "@radix-ui/themes";
import { SYMBOL_IDS, Icon as SimpleIcon } from "@/simple/Icon";
import { Icon as ProxyIcon } from "@/proxy/Icon";

/**
 * Shared interactive demo: renders an icon with either the simple/static helper
 * or the proxy helper (both generated by the CLI), with controls to switch icon
 * and color. `variant` is a plain string so it can be passed from the server
 * page components. The two helpers share the same symbol ids.
 */
export function IconPlayground({ variant }: { variant: "simple" | "proxy" }) {
  const [name, setName] = useState<(typeof SYMBOL_IDS)[number]>(SYMBOL_IDS[0]);
  const [color, setColor] = useState("#BADA55");
  const [currentColorOverride, setCurrentColorOverride] = useState(false);

  const fill = currentColorOverride ? "currentColor" : color;

  return (
    <Flex direction="column" gap="3" align="center">
      {variant === "proxy" ? (
        <ProxyIcon node={name} width={96} height={96} fill={fill} />
      ) : (
        <SimpleIcon node={name} width={96} height={96} fill={fill} />
      )}
      <Text as="p">Icon:</Text>
      <Select.Root
        value={name}
        onValueChange={(v) =>
          startTransition(() => setName(v as (typeof SYMBOL_IDS)[number]))
        }
      >
        <Select.Trigger>{name}</Select.Trigger>
        <Select.Content>
          {SYMBOL_IDS.map((id) => (
            <Select.Item key={id} value={id}>
              {id}
            </Select.Item>
          ))}
        </Select.Content>
      </Select.Root>
      <Text as="p">Color:</Text>
      <input
        type="color"
        defaultValue={color}
        onChange={(e) => startTransition(() => setColor(e.target.value))}
      />
      <Flex align="center" gap="2" asChild>
        <label>
          <Checkbox
            defaultChecked={currentColorOverride}
            onCheckedChange={(c) => setCurrentColorOverride(!!c)}
          />
          <Text>Use text color</Text>
        </label>
      </Flex>
    </Flex>
  );
}
